"""Generate notebooks/18_india_inventory_probe.ipynb."""

import json
from pathlib import Path

NB = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# India — inventory draw probe (PPAC + JODI)\n",
                "\n",
                "Validates implied stock change from PPAC **production**, **imports/exports** (combined trade workbook), and **consumption** vs JODI `STOCKCH` / `CLOSTLV`.\n",
                "\n",
                "Raw files:\n",
                "- `data/raw/india/trade/` — `PT_IMPORT_TMT_H.xlsx` + `PT_import.xls`\n",
                "- `data/raw/india/production/` — `PT_production_product_H.xls`\n",
                "- `data/processed/india/india_pt_consumption.parquet`\n",
                "- `data/processed/jodi/jodi_secondary.parquet`\n",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "import sys\n",
                "from pathlib import Path\n",
                "\n",
                "import plotly.express as px\n",
                "import plotly.graph_objects as go\n",
                "import pandas as pd\n",
                "\n",
                "for p in [Path.cwd(), Path.cwd().parent]:\n",
                "    if (p / 'analytics').is_dir() and (p / 'scripts').is_dir():\n",
                "        ROOT = p\n",
                "        break\n",
                "else:\n",
                "    raise RuntimeError('Run from country_oil_scraper or notebooks/')\n",
                "\n",
                "if str(ROOT) not in sys.path:\n",
                "    sys.path.insert(0, str(ROOT))\n",
                "\n",
                "from analytics.india_inventory import (\n",
                "    build_april_implied_inventory,\n",
                "    build_closing_stocks_summary,\n",
                "    build_ppac_closing_stocks_summary,\n",
                "    build_probe_tables,\n",
                "    cumulative_draw_since,\n",
                ")\n",
                "\n",
                "ANCHOR = '2026-02'\n",
                "WAR_BASELINE = pd.Timestamp('2026-02-01')\n",
                "tables = build_probe_tables(ROOT, anchor=ANCHOR)\n",
                "merged = tables['merged']\n",
                "jodi = tables['jodi_wide']\n",
                "draws = tables['cumulative_draws']\n",
                "draws",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 1. Cumulative draw since end-February (JODI headline)"],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "for prod in ['TOTPRODS', 'GASDIES', 'GASOLINE', 'LPG']:\n",
                "    d = cumulative_draw_since(jodi, ANCHOR, product=prod)\n",
                "    print(prod, d)\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Closing stocks by product since February 2026 (PPAC-timely)\n",
                "\n",
                "Same layout as Japan dashboard §8, but **monthly changes** use the latest **PPAC** refinery, trade, and demand (Excel + April PDF flash). PPAC does not publish stock **levels** — **Feb 2026** month-end levels are anchored on JODI **`CLOSTLV`** only.\n",
                "\n",
                "- **`change_kt_since_feb_ppac`** — sum of PPAC-implied monthly `STOCKCH` (Mar–Apr with current files)\n",
                "- **`latest_est_kt`** — Feb JODI level + that cumulative change\n",
                "- **`change_kt_jodi_levels`** — reference: JODI published closing levels through its latest month (often Mar)\n",
                "\n",
                "Months with demand only (no refinery output) are excluded from the balance.",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "ppac_stocks = build_ppac_closing_stocks_summary(ROOT, jodi, anchor=ANCHOR)\n",
                "print(ppac_stocks['source_note'])\n",
                "display(ppac_stocks['summary'].round(1))\n",
                "print(\n",
                "    f\"Panel sum change (Feb → {ppac_stocks['latest_ppac_period']}): \"\n",
                "    f\"{ppac_stocks['grand_change_ppac_kt']:+.0f} kt (PPAC-implied)\"\n",
                ")\n",
                "print(f\"JODI levels published through: {ppac_stocks['latest_jodi_period']}\")",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "total = ppac_stocks['totals_estimated_by_date'].copy().sort_values('date')\n",
                "recent = total[total['date'] >= '2025-10-01']\n",
                "fig = px.line(\n",
                "    recent,\n",
                "    x='date',\n",
                "    y='estimated_CLOSTLV',\n",
                "    title='India total product stocks (kt) — Feb JODI anchor + PPAC-implied path',\n",
                "    markers=True,\n",
                ")\n",
                "fig.add_shape(\n",
                "    type='line', x0=WAR_BASELINE, x1=WAR_BASELINE,\n",
                "    y0=0, y1=1, yref='paper',\n",
                "    line=dict(color='gray', width=1, dash='dash'),\n",
                ")\n",
                "fig.add_annotation(\n",
                "    x=WAR_BASELINE, y=1.02, xref='x', yref='paper',\n",
                "    text='Feb 2026 baseline', showarrow=False,\n",
                "    font=dict(color='gray', size=11),\n",
                ")\n",
                "fig.update_layout(height=420, template='plotly_white', yaxis_title='kt')\n",
                "fig.show()",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "flows = ppac_stocks['ppac_flows']\n",
                "mom = flows[flows['date'] >= '2025-10-01'].copy()\n",
                "fig2 = px.bar(\n",
                "    mom,\n",
                "    x='date',\n",
                "    y='implied_STOCKCH_ppac',\n",
                "    color='product_label',\n",
                "    barmode='relative',\n",
                "    title='Monthly stock change by product (kt) — PPAC-implied (+ = build)',\n",
                ")\n",
                "fig2.update_layout(height=460, template='plotly_white', yaxis_title='kt')\n",
                "fig2.show()",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 2b. JODI closing levels (reference — lags PPAC)\n",
                "\n",
                "Published **`CLOSTLV`** only; latest month is typically one behind PPAC trade/demand.",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "jodi_stocks = build_closing_stocks_summary(jodi, anchor=ANCHOR)\n",
                "display(jodi_stocks['summary'].round(1))\n",
                "print(\n",
                "    f\"JODI level change (Feb → {jodi_stocks['latest_period']}): \"\n",
                "    f\"{jodi_stocks['grand_change_kt']:+.0f} kt\"\n",
                ")",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. PPAC flows vs JODI (HSD / diesel)\n",
                "\n",
                "Stable few-% gaps → trade/production parsers align with JODI definitions.",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "hsd = merged[merged['jodi_product'] == 'GASDIES'].copy()\n",
                "hsd = hsd.dropna(subset=['ppac_refgrout', 'REFGROUT'])\n",
                "cols = ['TIME_PERIOD', 'ppac_refgrout', 'REFGROUT', 'ppac_imports', 'TOTIMPSB',\n",
                "        'ppac_exports', 'TOTEXPSB']\n",
                "hsd[cols].tail(12)",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "plot_df = hsd.dropna(subset=['STOCKCH', 'implied_STOCKCH_jodi_dem'])\n",
                "fig = go.Figure()\n",
                "fig.add_trace(go.Scatter(x=plot_df['TIME_PERIOD'].astype(str), y=plot_df['STOCKCH'],\n",
                "                         name='JODI STOCKCH', mode='lines+markers'))\n",
                "fig.add_trace(go.Scatter(x=plot_df['TIME_PERIOD'].astype(str), y=plot_df['implied_STOCKCH_jodi_dem'],\n",
                "                         name='Implied (PPAC supply, JODI demand)', mode='lines+markers'))\n",
                "fig.update_layout(title='HSD — implied vs JODI stock change (kt)', xaxis_title='Month', yaxis_title='kt')\n",
                "fig.show()",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. Gap diagnostics\n",
                "\n",
                "- `stockch_gap_jodi_dem` = implied (PPAC refinery+trade, JODI demand) − JODI `STOCKCH`\n",
                "- `stockch_gap` using PPAC demand shows the bunker/refinery-fuel wedge",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "from analytics.india_inventory import gap_diagnostics_summary\n",
                "\n",
                "gap_diagnostics_summary(merged)",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. April 2026 — implied inventory (PPAC demand + PDF trade/production)\n",
                "\n",
                "JODI is not available for April yet; this uses **PPAC consumption** and flash **PDFs** for supply.\n",
                "\n",
                "Sign convention (JODI): **positive `implied_STOCKCH` = stock build**; **positive `implied_draw` = stock draw**.",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "april = build_april_implied_inventory(ROOT, period='2026-04')\n",
                "display(april['headline'])\n",
                "april['by_jodi_product']",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "fig = px.bar(\n",
                "    april['by_jodi_product'],\n",
                "    x='jodi_product',\n",
                "    y='implied_STOCKCH_kt',\n",
                "    title='April 2026 implied stock change by product (kt) — PPAC only',\n",
                "    labels={'implied_STOCKCH_kt': 'Stock change (kt, + = build)'},\n",
                ")\n",
                "fig.add_hline(y=0, line_dash='dot')\n",
                "fig.show()",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

out = Path(__file__).resolve().parents[1] / "notebooks" / "18_india_inventory_probe.ipynb"
out.write_text(json.dumps(NB, indent=1), encoding="utf-8")
print(f"Wrote {out}")
